---

DISABLE_LINTERS:
  - SPELL_CSPELL
  - JAVA_PMD
  - REPOSITORY_KICS
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - COPYPASTE_JSCPD
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - SPELL_LYCHEE
  - MARKDOWN_MARKDOWN_LINK_CHECK

FILTER_REGEX_EXCLUDE: "(src/main/resources/static|script)"
