package tw.commonground.backend.service.user.entity;

public enum UserOccupation {
    STUDENTS,
    FREELANCERS_SELF_EMPLOYED,
    EDUCATION_ACADEMIA,
    HEALTHCARE_HEALTH,
    TECHNOLOGY_ENGINEERING,
    ARTS_DESIGN,
    FINANCE_LAW,
    PUBLIC_SERVICE,
    BUSINESS_SALES,
    MEDIA_COMMUNICATION,
    TRAVEL_HOSPITALITY,
    ENVIRONMENTAL_SCIENCE_POLICY,
    ENERGY_INFRASTRUCTURE,
    CONSTRUCTION_BUILDING,
    LOGISTICS_SUPPLY_CHAIN_MANAGEMENT,
    TRANSPORTATION_SERVICES,
    AGRICULTURAL_WORKERS,
    ENVIRONMENTAL_CONSERVATION_RESOURCE_MANAGEMENT,
    RETIRED_NOT_WORKING
}